-- {"id":909555555, "ver":"1.0.0","libVer":"1.0.0","author":"suhan-paradkar", "dep":["Madara>=2.2.0"]}

return Require("Madara")("https://1stkissnovel.org",{
	id = 909555555,
	name = "1stKissNovel.org",
	imageURL = "https://1stkissnovel.org/wp-content/uploads/2023/04/Im-3.png",

	novelListingURLPath = "anime",
	shrinkURLNovel = "novel",
	searchHasOper = false,

    genres = {
	"Action",
        "Adult",
        "Adventure",
	"Anime",
	"Apocalypse",
        "Comedy",
        "Completed",
        "Cooking",
        "Demons",
        "Detective",
        "Drama",
        "Ecchi",
        "Fan-Fiction",
        "Fantasy",
        "Food",
        "Game",
        "Girls Love",
        "Harem",
        "Historical",
        "Horror",
	"Humor",
        "Isekai",
        "Josei",
        "Magic",
        "Magical",
        "Manhua",
        "Manhwa",
        "Martial Arts",
        "Mature",
        "Mecha",
        "Medical",
        "Military",
        "Modern",
	"Murim",
        "Music",
        "Mystery",
        "Reverse",
        "Reverse harem",
        "Romance",
        "School Life",
        "Sci-fi",
        "Seinen",
        "Shoujo",
        "Shoujo Ai",
        "Shounen",
        "Shounen Ai",
        "Slice of life",
        "Smut",
        "Sports",
        "Super power",
        "Superhero",
        "Supernatural",
        "Thriller",
        "Tragedy",
        "Urban Life",
        "Vampire",
        "Webtoons",
        "Wuxia",
        "Xianxia",
        "Xuanhuan",
        "Yaoi",
        "Yuri"
	}
})
