-- {"id":9095, "ver":"1.0.5","libVer":"1.0.0","author":"suhan-paradkar", "dep":["Madara>=2.2.0"]}

return Require("Madara")("https://1stkissnovel.love",{
	id = 9095,
	name = "1stKissNovel",
	imageURL = "https://1stkissnovel.love/wp-content/uploads/2017/10/1STKISS_NOVEL.jpg",

	novelListingURLPath = "novel",
	shrinkURLNovel = "novel",
	searchHasOper = true,

    genres = {
		"Action",
        "Adult",
        "Adventure",
        "Comedy",
        "Completed",
        "Cooking",
        "Crime",
        "Demons",
        "Detective",
        "Drama",
        "Ecchi",
        "Fan-Fiction",
        "Fantasy",
        "Food",
        "Full Color",
        "Game",
        "Gender Bender",
        "Harem",
        "Historical",
        "Horror",
        "Isekai",
        "Josei",
        "Live Action",
        "Magic",
        "Magical",
        "Manga",
        "Manhua",
        "Manhwa",
        "Martial Arts",
        "Mature",
        "Mecha",
        "Medical",
        "Military",
        "Moder",
        "Modern",
        "Music",
        "Mystery",
        "One Shot",
        "Philosophical",
        "Psychological",
        "Reverse",
        "Reverse harem",
        "Romance",
        "School",
        "School Life",
        "Sci-fi",
        "Seinen",
        "Shoujo",
        "Shoujo Ai",
        "Shounen",
        "Shounen Ai",
        "Slice of life",
        "Smut",
        "Sports",
        "Super power",
        "Superhero",
        "Supernatural",
        "System",
        "Thriller",
        "Time Travel",
        "Tragedy",
        "Urban Life",
        "Vampire",
        "Webtoons",
        "Wuxia",
        "Xianxia",
        "Xuanhuan",
        "Yaoi",
        "Yuri"
	}
})
