-- {"id":9001, "ver":"1.0.4","libver":"1.0.0","author":"suhan-paradkar"}

return Require("WiseMadara")("https://daonovel.com/",{
	id = 9001,
	name = "DaoNovel",
	imageURL = "https://daonovel.com/wp-content/uploads/2019/02/White-logo-no-background.png",

	novelListingURLPath = "novels-list",
	shrinkURLNovel = "novels",
	searchHasOper = true,
        hasCloudFlare = true,

    genres = {
		"Action",
        "Adult",
        "Adventure",
        "Comedy",
        "Drama",
        "Ecchi",
        "Fantasy",
        "Gender Bender",
        "Harem",
        "Historical",
        "Horror",
        "Isekai",
        "Josei",
        "LGBT+",
        "Magical Realism",
        "Manhwa",
        "Martial Arts",
        "Mature",
        "Mecha",
        "Mystery",
        "Psychological",
        "Reincarnation",
        "Romance",
        "School Life",
        "Sci-fi",
        "Seinen",
        "Shoujo",
        "Shoujo Ai",
        "Shounen",
        "Shounen Ai",
        "Slice of life",
        "Smut",
        "Sports",
        "Supernatural",
        "Teen",
        "Thriller",
        "Tragedy",
        "Video Games",
        "Webcomics",
        "Wuxia",
        "Xianxia",
        "Xuanhuan",
        "Yuri"
	}
})
