return Require("Madara")("https://novelr18.com",{
	id = 9090,
	name = "NovelR18",
	imageURL = "https://novelr18.com/wp-content/uploads/2017/10/logo_.png",

	novelListingURLPath = "novel",
	shrinkURLNovel = "manga",
	searchHasOper = true,
        latestNovelSel = "div.col-6.col-md-2.badge-pos-1",
        hasCloudFlare = true,
        ajaxUsesFormData = true,

    genres = {
		"Action",
        "Adult",
        "Adventure",
        "Comedy",
        "China",
        "Drama",
        "Ecchi",
        "Fanfiction",
        "Fantasy",
        "Game",
        "Gender Bender",
        "Girls Love",
        "Harem",
        "Isekai",
        "Japan",
        "Josei",
        "Korea",
        "LitRPG",
        "Martial Arts",
        "Mature",
        "Mystery",
        "Original",
        "Psychological",
        "Romance",
        "School Life",
        "Sci-fi",
        "Seinen",
        "Shoujo",
        "Slice of life",
        "Smut",
        "Supernatural",
        "Tragedy",
        "Xianxia",
        "Xuanhuan",
        "Yuri"
	}
})
