-- {"id":7018, "ver":"1.0.3","libver":"1.0.0","author":"suhan-paradkar","dep":["WiseMadara>=2.2.0"]}

return Require("WiseMadara")("https://www.novelmultiverse.com",{
	id = 7018,
	name = "NovelMultiverse",
	imageURL = "https://www.novelmultiverse.com/wp-content/uploads/2020/04/novelmultiverse-48x48-2.png",

	novelListingURLPath = "novels",
	shrinkURLNovel = "novel",

    genres = {
		"Action",
        "Adult",
        "Adventure",
        "Cartoon",
        "Comedy",
        "Comic",
        "Cooking",
        "Detective",
        "Doujinshi",
        "Drama",
        "Ecchi",
        "Fantasy",
        "Gender Bender",
        "Harem",
        "Historical",
        "Horror",
        "Josei",
        "Live Action",
        "Manga",
        "Manhua",
        "Manhwa",
        "Martial Arts",
        "Mature",
        "Mecha",
        "Mystery",
        "One Shot",
        "Original",
        "Psychological",
        "Romance",
        "School Life",
        "Sci-fi",
        "Seinen",
        "Shoujo",
        "Shoujo Ai",
        "Shounen",
        "Shounen Ai",
        "Slice of life",
        "Smut",
        "Soft Yaoi",
        "Soft Yuri",
        "Sports",
        "Supernatural",
        "Tragedy",
        "Translation",
        "Webtoon",
        "Xianxia",
        "Xuanhuan",
        "Yaoi",
        "Yuri"
	}
})
