return Require("Madara")("https://vipnovel.com",{
	id = 8015,
	name = "VIPNovel",
	imageURL = "https://vipnovel.com/wp-content/uploads/2017/10/coollogo_com-1630861.png",

	novelListingURLPath = "vipnovel",
	shrinkURLNovel = "vipnovel",
	searchHasOper = true,

    genres = {
		"Action",
        "Adult",
        "Adventure",
        "BL",
        "Comedy",
        "Contemporary Romance",
        "Drama",
        "Eastern",
        "Ecchi",
        "Fantasy",
        "Gender Bender",
        "Harem",
        "Historical",
        "Horror",
        "Isekai",
        "Josei",
        "LGBT+",
        "Magic",
        "Magical Realism",
        "Martial Arts",
        "Mature",
        "Mecha",
        "Mystery",
        "Psychological",
        "Romance",
        "School Life",
        "Sci-fi",
        "Seinen",
        "Shoujo",
        "Shounen",
        "Slice of life",
        "Smut",
        "Sports",
        "Supernatural",
        "Tragedy",
        "Video Games",
        "Wuxia",
        "Xianxia",
        "Xuanhuan",
        "Yaoi",
        "Yuri"
	}
})
